import { SkolskiSati } from './SkolskiSati';

export const skolskiSati: SkolskiSati[] = [
  {
    interval: { pocetak: { sati: 0, minute: 0 }, kraj: { sati: 8, minute: 0 } },
    poruka: { kratkaPoruka: 'Nastava još nije počela.', dugaPoruka: 'Jutarnja nastava još nije počela.' },
    nastavaUTijeku: false,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 0,
    satUTijeku: false,
    smjena: 'van',
    image: 'clock.jpg',
  },
  {
    interval: { pocetak: { sati: 8, minute: 0 }, kraj: { sati: 8, minute: 40 } },
    poruka: { kratkaPoruka: '1. sat', dugaPoruka: '1. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 1,
    satUTijeku: true,
    smjena: 'jutarnja',
    image: '1.jpg',
  },
  {
    interval: { pocetak: { sati: 8, minute: 40 }, kraj: { sati: 8, minute: 45 } },
    poruka: { kratkaPoruka: 'Mali odmor', dugaPoruka: 'Mali odmor poslije 1. sata je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: false,
    sat: 1,
    satUTijeku: false,
    smjena: 'jutarnja',
    image: '1-2.jpg',
  },
  {
    interval: { pocetak: { sati: 8, minute: 45 }, kraj: { sati: 9, minute: 25 } },
    poruka: { kratkaPoruka: '2. sat', dugaPoruka: '2. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 2,
    satUTijeku: true,
    smjena: 'jutarnja',
    image: '2.jpg',
  },
  {
    interval: { pocetak: { sati: 9, minute: 25 }, kraj: { sati: 9, minute: 30 } },
    poruka: { kratkaPoruka: 'Mali odmor', dugaPoruka: 'Mali odmor poslije 2. sata je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: false,
    sat: 2,
    satUTijeku: false,
    smjena: 'jutarnja',
    image: '2-3.jpg',
  },
  {
    interval: { pocetak: { sati: 9, minute: 30 }, kraj: { sati: 10, minute: 10 } },
    poruka: { kratkaPoruka: '3. sat', dugaPoruka: '3. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 3,
    satUTijeku: true,
    smjena: 'jutarnja',
    image: '3.jpg',
  },
  {
    interval: { pocetak: { sati: 10, minute: 10 }, kraj: { sati: 10, minute: 25 } },
    poruka: { kratkaPoruka: 'Veliki odmor', dugaPoruka: 'Veliki odmor je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: true,
    sat: 3,
    satUTijeku: false,
    smjena: 'jutarnja',
    image: '3-4.jpg',
  },
  {
    interval: { pocetak: { sati: 10, minute: 25 }, kraj: { sati: 11, minute: 5 } },
    poruka: { kratkaPoruka: '4. sat', dugaPoruka: '4. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 4,
    satUTijeku: true,
    smjena: 'jutarnja',
    image: '4.jpg',
  },
  {
    interval: { pocetak: { sati: 11, minute: 5 }, kraj: { sati: 11, minute: 10 } },
    poruka: { kratkaPoruka: 'Mali odmor', dugaPoruka: 'Mali odmor poslije 4. sata je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: false,
    sat: 4,
    satUTijeku: false,
    smjena: 'jutarnja',
    image: '4-5.jpg',
  },
  {
    interval: { pocetak: { sati: 11, minute: 10 }, kraj: { sati: 11, minute: 50 } },
    poruka: { kratkaPoruka: '5. sat', dugaPoruka: '5. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 5,
    satUTijeku: true,
    smjena: 'jutarnja',
    image: '5.jpg',
  },
  {
    interval: { pocetak: { sati: 11, minute: 50 }, kraj: { sati: 11, minute: 55 } },
    poruka: { kratkaPoruka: 'Mali odmor', dugaPoruka: 'Mali odmor poslije 5. sata je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: false,
    sat: 5,
    satUTijeku: false,
    smjena: 'jutarnja',
    image: '5-6.jpg',
  },
  {
    interval: { pocetak: { sati: 11, minute: 55 }, kraj: { sati: 12, minute: 35 } },
    poruka: { kratkaPoruka: '6. sat', dugaPoruka: '6. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 6,
    satUTijeku: true,
    smjena: 'jutarnja',
    image: '6.jpg',
  },
  {
    interval: { pocetak: { sati: 12, minute: 35 }, kraj: { sati: 12, minute: 40 } },
    poruka: { kratkaPoruka: 'Mali odmor', dugaPoruka: 'Mali odmor poslije 6. sata je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: false,
    sat: 6,
    satUTijeku: false,
    smjena: 'jutarnja',
    image: '6-7.jpg',
  },
  {
    interval: { pocetak: { sati: 12, minute: 40 }, kraj: { sati: 13, minute: 20 } },
    poruka: { kratkaPoruka: '7. sat', dugaPoruka: '7. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 7,
    satUTijeku: true,
    smjena: 'jutarnja',
    image: '7.jpg',
  },
  {
    interval: { pocetak: { sati: 13, minute: 20 }, kraj: { sati: 14, minute: 0 } },
    poruka: { kratkaPoruka: 'Između nastave', dugaPoruka: 'Jutarnja smjena je završila, popodnevna još nije počela.' },
    nastavaUTijeku: false,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 0,
    satUTijeku: false,
    smjena: 'van',
    image: 'sat.jpg',
  },
  {
    interval: { pocetak: { sati: 14, minute: 0 }, kraj: { sati: 14, minute: 40 } },
    poruka: { kratkaPoruka: '1. sat', dugaPoruka: '1. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 1,
    satUTijeku: true,
    smjena: 'popodnevna',
    image: '1.jpg',
  },
  {
    interval: { pocetak: { sati: 14, minute: 40 }, kraj: { sati: 14, minute: 45 } },
    poruka: { kratkaPoruka: 'Mali odmor', dugaPoruka: 'Mali odmor poslije 1. sata je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: false,
    sat: 1,
    satUTijeku: false,
    smjena: 'popodnevna',
    image: '1-2.jpg',
  },
  {
    interval: { pocetak: { sati: 14, minute: 45 }, kraj: { sati: 15, minute: 25 } },
    poruka: { kratkaPoruka: '2. sat', dugaPoruka: '2. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 2,
    satUTijeku: true,
    smjena: 'popodnevna',
    image: '2.jpg',
  },
  {
    interval: { pocetak: { sati: 15, minute: 25 }, kraj: { sati: 15, minute: 30 } },
    poruka: { kratkaPoruka: 'Mali odmor', dugaPoruka: 'Mali odmor poslije 2. sata je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: false,
    sat: 2,
    satUTijeku: false,
    smjena: 'popodnevna',
    image: '2-3.jpg',
  },
  {
    interval: { pocetak: { sati: 15, minute: 30 }, kraj: { sati: 16, minute: 10 } },
    poruka: { kratkaPoruka: '3. sat', dugaPoruka: '3. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 3,
    satUTijeku: true,
    smjena: 'popodnevna',
    image: '3.jpg',
  },
  {
    interval: { pocetak: { sati: 16, minute: 10 }, kraj: { sati: 16, minute: 25 } },
    poruka: { kratkaPoruka: 'Veliki odmor', dugaPoruka: 'Veliki odmor je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: true,
    sat: 3,
    satUTijeku: false,
    smjena: 'popodnevna',
    image: '3-4.jpg',
  },
  {
    interval: { pocetak: { sati: 16, minute: 25 }, kraj: { sati: 17, minute: 5 } },
    poruka: { kratkaPoruka: '4. sat', dugaPoruka: '4. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 4,
    satUTijeku: true,
    smjena: 'popodnevna',
    image: '4.jpg',
  },
  {
    interval: { pocetak: { sati: 17, minute: 5 }, kraj: { sati: 17, minute: 10 } },
    poruka: { kratkaPoruka: 'Mali odmor', dugaPoruka: 'Mali odmor poslije 4. sata je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: false,
    sat: 4,
    satUTijeku: false,
    smjena: 'popodnevna',
    image: '4-5.jpg',
  },
  {
    interval: { pocetak: { sati: 17, minute: 10 }, kraj: { sati: 17, minute: 50 } },
    poruka: { kratkaPoruka: '5. sat', dugaPoruka: '5. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 5,
    satUTijeku: true,
    smjena: 'popodnevna',
    image: '5.jpg',
  },
  {
    interval: { pocetak: { sati: 17, minute: 50 }, kraj: { sati: 17, minute: 55 } },
    poruka: { kratkaPoruka: 'Mali odmor', dugaPoruka: 'Mali odmor poslije 5. sata je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: false,
    sat: 5,
    satUTijeku: false,
    smjena: 'popodnevna',
    image: '5-6.jpg',
  },
  {
    interval: { pocetak: { sati: 17, minute: 55 }, kraj: { sati: 18, minute: 35 } },
    poruka: { kratkaPoruka: '6. sat', dugaPoruka: '6. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 6,
    satUTijeku: true,
    smjena: 'popodnevna',
    image: '6.jpg',
  },
  {
    interval: { pocetak: { sati: 18, minute: 35 }, kraj: { sati: 18, minute: 40 } },
    poruka: { kratkaPoruka: 'Mali odmor', dugaPoruka: 'Mali odmor poslije 6. sata je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: true,
    velikiOdmor: false,
    sat: 6,
    satUTijeku: false,
    smjena: 'popodnevna',
    image: '6-7.jpg',
  },
  {
    interval: { pocetak: { sati: 18, minute: 40 }, kraj: { sati: 19, minute: 20 } },
    poruka: { kratkaPoruka: '7. sat', dugaPoruka: '7. sat je u tijeku.' },
    nastavaUTijeku: true,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 7,
    satUTijeku: true,
    smjena: 'popodnevna',
    image: '7.jpg',
  },
  {
    interval: { pocetak: { sati: 19, minute: 20 }, kraj: { sati: 23, minute: 59 } },
    poruka: { kratkaPoruka: 'Nastava je završila.', dugaPoruka: 'Popodnevna nastava je završila.' },
    nastavaUTijeku: false,
    doKraja: 0,
    odPocetka: 0,
    odmor: false,
    velikiOdmor: false,
    sat: 0,
    satUTijeku: false,
    smjena: 'van',
    image: 'clock.jpg',
  },
];
